# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mars' Linksite
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  All my info and links
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mars.squirrel.pub" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll


favicon: /assets/base/paw.svg
og_image: /assets/base/Squirrelbite Flyer website.png

header_socials:
  - name: Mastodon
    icon: /assets/icons/icon_mastodon.svg
    link: https://squirrel.pub/@mars
  - name: Bluesky
    icon: /assets/icons/icon_bluesky.svg
    link: https://bsky.app/profile/mars.squirrel.pub
  - name: Twatter
    icon: /assets/icons/icon_twatter.svg
    link: https://twitter.com/Emperor_of_Mars
  - name: Furaffinity
    icon: /assets/icons/icon_furaffinity.png
    link: https://www.furaffinity.net/user/emperorofmars
  - name: Furtrack
    icon: /assets/icons/icon_furtrack.png
    link: https://www.furtrack.com/user/mars/fursuiting
  - name: Youtube
    icon: /assets/icons/icon_youtube.svg
    link: https://www.youtube.com/@emperor_of_mars
  - name: Github
    icon: /assets/icons/icon_github.svg
    link: https://github.com/emperorofmars

meta_see_also:
  - "https://squirrelbite.com"
  - "https://squirrel.pub/@mars"
  - "https://bsky.app/profile/mars.squirrel.pub"
  - "https://www.furaffinity.net/user/emperorofmars"
  - "https://twitter.com/Emperor_of_Mars"
  - "https://github.com/emperorofmars"
  - "https://emperorofmars.itch.io/"
  - "https://squirrelbite.itch.io/"
  - "https://jinxxy.com/squirrelbite/products"
  - "https://squirrelbite.gumroad.com/"
  - "https://www.youtube.com/@emperor_of_mars"
  - "https://www.furtrack.com/user/mars/fursuiting"

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
# - jekyll-minifier

sass:
  sass_dir: _sass
#  style: compressed

include: [".well-known", ".htaccess"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
